import React, { createContext, useState, useContext, useEffect, useMemo } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    dashboard: 'Dashboard',
    exercises: 'Exercises',
    profile: 'Profile',
    chat: 'Chat',
    support: 'Support',
    messages: 'Messages',
    progressReport: 'Progress Report',
    logout: 'Logout',
    loadingExercises: 'Loading exercises...',
    exerciseLibraryTitle: 'Exercise Library',
    exerciseLibrarySubtitle: 'Browse and start your personalized rehabilitation exercises',
    exerciseTrackingTitle: 'Exercise Tracking',
    myExercises: 'My Exercises',
    searchExercises: 'Search exercises...',
    allExercises: 'All Exercises',
    knee: 'Knee',
    shoulder: 'Shoulder',
    back: 'Back',
    hip: 'Hip',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    totalExercises: 'Total Exercises',
    completed: 'Completed',
    thisWeek: 'This Week',
    noExercisesFound: 'No exercises found',
    tryDifferentSearch: 'Try a different search term',
    selectAnotherCategory: 'Select another category',
    watchVideoReference: 'Watch video reference',
    editProfile: 'Edit Profile',
    startExercise: 'Start Exercise',
    clearSelection: 'Clear Selection',
    personalInformation: 'Personal Information',
    medicalInformation: 'Medical Information',
    achievements: 'Achievements',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    age: 'Age',
    injuryType: 'Condition',
    rehabilitationPlan: 'Rehabilitation Plan',
    medicalHistory: 'Medical History',
    currentConditions: 'Current Conditions',
    noData: 'Not available',
    selected: 'Selected',
    completedSetsReps: 'Completed Sets / Reps *',
    painLevel: 'Pain Level (0-10)',
    notes: 'Notes',
    enableWebcam: 'Enable webcam for real-time form correction',
    startTracking: 'Start Tracking',
    stopTracking: 'Stop Tracking',
    supportTitle: 'Support & Medical Professionals',
    supportSubtitle: 'Connect with expert professionals for personalized guidance',
    findProfessionals: 'Find Professionals',
    activeChats: 'Active Chats',
    allProfessionals: 'All Professionals',
    sportsMedicine: 'Sports Medicine',
    postSurgeryRecovery: 'Post-Surgery Recovery',
    searchByNameOrSpecialty: 'Search by name or specialty...',
    noProfessionalsFound: 'No professionals found',
    tryAdjustingSearchFilters: 'Try adjusting your search filters',
    verifiedProfessional: 'Verified professional',
    verificationPending: 'Verification pending',
    availableForAppointment: 'Available for appointment',
    yourActiveConversations: 'Your active conversations with medical professionals',
    noActiveChats: 'No active chats',
    startConversationHint: 'Start a conversation with a professional to see it here',
    openChat: 'Open Chat',
    noEmailAvailable: 'No email available',
    unknownUser: 'Unknown User',
    loadingMessages: 'Loading messages...',
    conversations: 'Conversations',
    startMessageWithAssignedDoctor: 'Start Message With Assigned Doctor',
    noConversationsYet: 'No conversations yet',
    noMessagesYetStart: 'No messages yet. Start the conversation!',
    selectConversationToStartMessaging: 'Select a conversation to start messaging',
    typeMessage: 'Type a message...',
    send: 'Send',
    sending: 'Sending...',
    noMessagesYet: 'No messages yet',
    justNow: 'Just now',
    call: 'Call',
    video: 'Video',
    yourRecoveryProgressAndPlans: 'Your recovery progress and treatment plans',
    overview: 'Overview',
    assignedExercisesLabel: 'Assigned Exercises',
    dietPlansLabel: 'Diet Plans',
    assignedDoctor: 'Assigned Doctor',
    awaitingAssignment: 'Awaiting Assignment',
    yourMedicalProfessional: 'Your Medical Professional',
    contactDoctor: 'Contact Doctor',
    noDoctorAssignedYet: 'No doctor assigned yet',
    doctorWillAppear: 'Your assigned doctor will appear here once they connect with you',
    aiRecoveryInsights: 'AI Recovery Insights',
    recentAvgPain: 'Recent Avg Pain',
    exerciseProgress: 'Exercise Progress',
    overallProgress: 'Overall Progress',
    pending: 'Pending',
    recentActivity: 'Recent Activity',
    noExercisesYet: 'No exercises yet',
    exercisesAssignedWillAppear: 'Exercises assigned by your doctor will appear here',
    assignedOn: 'Assigned',
    doctorMyPatients: 'My Patients',
    doctorAssignedPatients: 'Assigned Patients',
    doctorCompletedSessions: 'Completed Sessions',
    doctorPendingSessions: 'Pending Sessions',
    doctorAvgAdherence: 'Avg Adherence',
    doctorShortPrefix: 'Dr.',
    doctorDashboardSubtitle: 'Manage your assigned patients and their treatment plans',
    doctorClinicalSnapshot: 'Clinical Snapshot',
    doctorTodayPanel: "Today's Panel",
    doctorHighestPainTrend: 'Highest pain trend',
    doctorNoHighRiskAlerts: 'No high-risk alerts yet. Assign patients to start tracking trends.',
    doctorExercisesLogged: 'Exercises Logged',
    doctorAvgPain: 'Avg Pain',
    doctorAssignPatient: 'Assign Patient',
    doctorSearchPatients: 'Search by name, email or condition',
    doctorSortName: 'Sort: Name (A-Z)',
    doctorSortCompletion: 'Sort: Completion Rate',
    doctorSortPain: 'Sort: Avg Pain Level',
    doctorSortPending: 'Sort: Pending Sessions',
    doctorAllAdherenceBands: 'All Adherence Bands',
    doctorHighAdherence: 'High Adherence (75%+)',
    doctorMediumAdherence: 'Medium Adherence (40-74%)',
    doctorLowAdherence: 'Low Adherence (<40%)',
    doctorNoPatientsAssigned: 'No patients assigned yet',
    doctorAssignPatientsToStart: 'Assign patients to get started',
    doctorNoPatientsAvailable: 'No patients available in the system',
    doctorNoMatchingPatients: 'No matching patients',
    doctorTryDifferentSearch: 'Try a different search term or adjust the adherence filter',
    mainDashboardWelcomeTitle: 'Welcome to RehabAI Dashboard',
    mainDashboardLoginPrompt: 'Please log in to access the dashboard features.',
    mainDashboardWelcomeUser: 'Welcome',
    mainDashboardLoggedInAs: 'You are logged in as',
    mainDashboardPatients: 'Patients',
    mainDashboardPatientsDesc: 'Manage patient information and progress',
    mainDashboardViewPatients: 'View Patients',
    mainDashboardExercisesDesc: 'Browse and create rehabilitation exercises',
    mainDashboardViewExercises: 'View Exercises',
    mainDashboardSessions: 'Sessions',
    mainDashboardSessionsDesc: 'Track exercise sessions and progress',
    mainDashboardViewSessions: 'View Sessions'
  },
  es: {
    dashboard: 'Panel principal',
    exercises: 'Ejercicios',
    profile: 'Perfil',
    chat: 'Chat',
    support: 'Soporte',
    messages: 'Mensajes',
    progressReport: 'Informe de progreso',
    logout: 'Cerrar sesión',
    loadingExercises: 'Cargando ejercicios...',
    exerciseLibraryTitle: 'Biblioteca de ejercicios',
    exerciseLibrarySubtitle: 'Explora y comienza tus ejercicios de rehabilitación personalizados',
    exerciseTrackingTitle: 'Seguimiento de ejercicios',
    myExercises: 'Mis ejercicios',
    searchExercises: 'Buscar ejercicios...',
    allExercises: 'Todos los ejercicios',
    knee: 'Rodilla',
    shoulder: 'Hombro',
    back: 'Espalda',
    hip: 'Cadera',
    beginner: 'Principiante',
    intermediate: 'Intermedio',
    advanced: 'Avanzado',
    totalExercises: 'Ejercicios totales',
    completed: 'Completados',
    thisWeek: 'Esta semana',
    noExercisesFound: 'No se encontraron ejercicios',
    tryDifferentSearch: 'Prueba otro término de búsqueda',
    selectAnotherCategory: 'Selecciona otra categoría',
    watchVideoReference: 'Ver referencia en video',
    editProfile: 'Editar perfil',
    startExercise: 'Comenzar ejercicio',
    clearSelection: 'Limpiar selección',
    personalInformation: 'Información personal',
    medicalInformation: 'Información médica',
    achievements: 'Logros',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
    firstName: 'Nombre',
    lastName: 'Apellido',
    emailAddress: 'Correo electrónico',
    phoneNumber: 'Número de teléfono',
    age: 'Edad',
    injuryType: 'Condición',
    rehabilitationPlan: 'Plan de rehabilitación',
    medicalHistory: 'Historial médico',
    currentConditions: 'Condiciones actuales',
    noData: 'No disponible',
    selected: 'Seleccionado',
    completedSetsReps: 'Series / repeticiones completadas *',
    painLevel: 'Nivel de dolor (0-10)',
    notes: 'Notas',
    enableWebcam: 'Activa la cámara para corregir la postura en tiempo real',
    startTracking: 'Iniciar seguimiento',
    stopTracking: 'Detener seguimiento',
    supportTitle: 'Soporte y profesionales médicos',
    supportSubtitle: 'Conéctate con profesionales expertos para una guía personalizada',
    findProfessionals: 'Buscar profesionales',
    activeChats: 'Chats activos',
    allProfessionals: 'Todos los profesionales',
    sportsMedicine: 'Medicina deportiva',
    postSurgeryRecovery: 'Recuperación postquirúrgica',
    searchByNameOrSpecialty: 'Buscar por nombre o especialidad...',
    noProfessionalsFound: 'No se encontraron profesionales',
    tryAdjustingSearchFilters: 'Intenta ajustar tus filtros de búsqueda',
    verifiedProfessional: 'Profesional verificado',
    verificationPending: 'Verificación pendiente',
    availableForAppointment: 'Disponible para cita',
    yourActiveConversations: 'Tus conversaciones activas con profesionales médicos',
    noActiveChats: 'No hay chats activos',
    startConversationHint: 'Inicia una conversación con un profesional para verla aquí',
    openChat: 'Abrir chat',
    noEmailAvailable: 'Correo no disponible',
    unknownUser: 'Usuario desconocido',
    loadingMessages: 'Cargando mensajes...',
    conversations: 'Conversaciones',
    startMessageWithAssignedDoctor: 'Iniciar mensaje con doctor asignado',
    noConversationsYet: 'Aún no hay conversaciones',
    noMessagesYetStart: 'Aún no hay mensajes. ¡Inicia la conversación!',
    selectConversationToStartMessaging: 'Selecciona una conversación para comenzar a chatear',
    typeMessage: 'Escribe un mensaje...',
    send: 'Enviar',
    sending: 'Enviando...',
    noMessagesYet: 'Aún no hay mensajes',
    justNow: 'Justo ahora',
    call: 'Llamar',
    video: 'Video',
    yourRecoveryProgressAndPlans: 'Tu progreso de recuperación y planes de tratamiento',
    overview: 'Resumen',
    assignedExercisesLabel: 'Ejercicios asignados',
    dietPlansLabel: 'Planes de dieta',
    assignedDoctor: 'Doctor asignado',
    awaitingAssignment: 'Esperando asignación',
    yourMedicalProfessional: 'Tu profesional médico',
    contactDoctor: 'Contactar doctor',
    noDoctorAssignedYet: 'Aún no tienes doctor asignado',
    doctorWillAppear: 'Tu doctor asignado aparecerá aquí cuando se conecte contigo',
    aiRecoveryInsights: 'Información de recuperación por IA',
    recentAvgPain: 'Promedio reciente de dolor',
    exerciseProgress: 'Progreso de ejercicios',
    overallProgress: 'Progreso general',
    pending: 'Pendiente',
    recentActivity: 'Actividad reciente',
    noExercisesYet: 'Aún no hay ejercicios',
    exercisesAssignedWillAppear: 'Los ejercicios asignados por tu doctor aparecerán aquí',
    assignedOn: 'Asignado',
    doctorMyPatients: 'Mis pacientes',
    doctorAssignedPatients: 'Pacientes asignados',
    doctorCompletedSessions: 'Sesiones completadas',
    doctorPendingSessions: 'Sesiones pendientes',
    doctorAvgAdherence: 'Adherencia promedio',
    doctorShortPrefix: 'Dr.',
    doctorDashboardSubtitle: 'Gestiona tus pacientes asignados y sus planes de tratamiento',
    doctorClinicalSnapshot: 'Resumen clínico',
    doctorTodayPanel: 'Panel de hoy',
    doctorHighestPainTrend: 'Mayor tendencia de dolor',
    doctorNoHighRiskAlerts: 'Aún no hay alertas de alto riesgo. Asigna pacientes para comenzar a seguir tendencias.',
    doctorExercisesLogged: 'Ejercicios registrados',
    doctorAvgPain: 'Dolor promedio',
    doctorAssignPatient: 'Asignar paciente',
    doctorSearchPatients: 'Buscar por nombre, correo o condición',
    doctorSortName: 'Ordenar: Nombre (A-Z)',
    doctorSortCompletion: 'Ordenar: Tasa de finalización',
    doctorSortPain: 'Ordenar: Dolor promedio',
    doctorSortPending: 'Ordenar: Sesiones pendientes',
    doctorAllAdherenceBands: 'Todas las bandas de adherencia',
    doctorHighAdherence: 'Alta adherencia (75%+)',
    doctorMediumAdherence: 'Adherencia media (40-74%)',
    doctorLowAdherence: 'Baja adherencia (<40%)',
    doctorNoPatientsAssigned: 'Aún no hay pacientes asignados',
    doctorAssignPatientsToStart: 'Asigna pacientes para comenzar',
    doctorNoPatientsAvailable: 'No hay pacientes disponibles en el sistema',
    doctorNoMatchingPatients: 'No hay pacientes coincidentes',
    doctorTryDifferentSearch: 'Prueba otro término de búsqueda o ajusta el filtro de adherencia',
    mainDashboardWelcomeTitle: 'Bienvenido al panel de RehabAI',
    mainDashboardLoginPrompt: 'Inicia sesión para acceder a las funciones del panel.',
    mainDashboardWelcomeUser: 'Bienvenido',
    mainDashboardLoggedInAs: 'Has iniciado sesión como',
    mainDashboardPatients: 'Pacientes',
    mainDashboardPatientsDesc: 'Gestiona la información y el progreso de los pacientes',
    mainDashboardViewPatients: 'Ver pacientes',
    mainDashboardExercisesDesc: 'Explora y crea ejercicios de rehabilitación',
    mainDashboardViewExercises: 'Ver ejercicios',
    mainDashboardSessions: 'Sesiones',
    mainDashboardSessionsDesc: 'Supervisa sesiones de ejercicios y progreso',
    mainDashboardViewSessions: 'Ver sesiones'
  },
  fr: {
    dashboard: 'Tableau de bord',
    exercises: 'Exercices',
    profile: 'Profil',
    chat: 'Chat',
    support: 'Assistance',
    messages: 'Messages',
    progressReport: 'Rapport de progression',
    logout: 'Déconnexion',
    loadingExercises: 'Chargement des exercices...',
    exerciseLibraryTitle: 'Bibliothèque d’exercices',
    exerciseLibrarySubtitle: 'Parcourez et démarrez vos exercices de rééducation personnalisés',
    exerciseTrackingTitle: 'Suivi des exercices',
    myExercises: 'Mes exercices',
    searchExercises: 'Rechercher des exercices...',
    allExercises: 'Tous les exercices',
    knee: 'Genou',
    shoulder: 'Épaule',
    back: 'Dos',
    hip: 'Hanche',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    advanced: 'Avancé',
    totalExercises: 'Exercices totaux',
    completed: 'Terminés',
    thisWeek: 'Cette semaine',
    noExercisesFound: 'Aucun exercice trouvé',
    tryDifferentSearch: 'Essayez un autre terme de recherche',
    selectAnotherCategory: 'Sélectionnez une autre catégorie',
    watchVideoReference: 'Voir la référence vidéo',
    editProfile: 'Modifier le profil',
    startExercise: 'Démarrer l’exercice',
    clearSelection: 'Effacer la sélection',
    personalInformation: 'Informations personnelles',
    medicalInformation: 'Informations médicales',
    achievements: 'Réalisations',
    saveChanges: 'Enregistrer les modifications',
    cancel: 'Annuler',
    firstName: 'Prénom',
    lastName: 'Nom',
    emailAddress: 'Adresse e-mail',
    phoneNumber: 'Numéro de téléphone',
    age: 'Âge',
    injuryType: 'État',
    rehabilitationPlan: 'Plan de rééducation',
    medicalHistory: 'Antécédents médicaux',
    currentConditions: 'Conditions actuelles',
    noData: 'Indisponible',
    selected: 'Sélectionné',
    completedSetsReps: 'Séries / répétitions effectuées *',
    painLevel: 'Niveau de douleur (0-10)',
    notes: 'Notes',
    enableWebcam: 'Activer la webcam pour corriger la posture en temps réel',
    startTracking: 'Démarrer le suivi',
    stopTracking: 'Arrêter le suivi',
    supportTitle: 'Assistance et professionnels de santé',
    supportSubtitle: 'Connectez-vous avec des professionnels experts pour un accompagnement personnalisé',
    findProfessionals: 'Trouver des professionnels',
    activeChats: 'Chats actifs',
    allProfessionals: 'Tous les professionnels',
    sportsMedicine: 'Médecine du sport',
    postSurgeryRecovery: 'Récupération post-opératoire',
    searchByNameOrSpecialty: 'Rechercher par nom ou spécialité...',
    noProfessionalsFound: 'Aucun professionnel trouvé',
    tryAdjustingSearchFilters: 'Essayez d’ajuster les filtres de recherche',
    verifiedProfessional: 'Professionnel vérifié',
    verificationPending: 'Vérification en attente',
    availableForAppointment: 'Disponible pour rendez-vous',
    yourActiveConversations: 'Vos conversations actives avec des professionnels de santé',
    noActiveChats: 'Aucun chat actif',
    startConversationHint: 'Commencez une conversation avec un professionnel pour la voir ici',
    openChat: 'Ouvrir le chat',
    noEmailAvailable: 'E-mail indisponible',
    unknownUser: 'Utilisateur inconnu',
    loadingMessages: 'Chargement des messages...',
    conversations: 'Conversations',
    startMessageWithAssignedDoctor: 'Démarrer un message avec le médecin assigné',
    noConversationsYet: 'Aucune conversation pour le moment',
    noMessagesYetStart: 'Aucun message pour le moment. Lancez la conversation !',
    selectConversationToStartMessaging: 'Sélectionnez une conversation pour commencer à discuter',
    typeMessage: 'Tapez un message...',
    send: 'Envoyer',
    sending: 'Envoi...',
    noMessagesYet: 'Aucun message pour le moment',
    justNow: 'À l\'instant',
    call: 'Appeler',
    video: 'Vidéo',
    yourRecoveryProgressAndPlans: 'Votre progression de récupération et vos plans de traitement',
    overview: 'Vue d’ensemble',
    assignedExercisesLabel: 'Exercices assignés',
    dietPlansLabel: 'Plans alimentaires',
    assignedDoctor: 'Médecin assigné',
    awaitingAssignment: 'En attente d’assignation',
    yourMedicalProfessional: 'Votre professionnel de santé',
    contactDoctor: 'Contacter le médecin',
    noDoctorAssignedYet: 'Aucun médecin assigné pour le moment',
    doctorWillAppear: 'Votre médecin assigné apparaîtra ici une fois connecté avec vous',
    aiRecoveryInsights: 'Informations de récupération IA',
    recentAvgPain: 'Douleur moyenne récente',
    exerciseProgress: 'Progression des exercices',
    overallProgress: 'Progression globale',
    pending: 'En attente',
    recentActivity: 'Activité récente',
    noExercisesYet: 'Aucun exercice pour le moment',
    exercisesAssignedWillAppear: 'Les exercices assignés par votre médecin apparaîtront ici',
    assignedOn: 'Assigné',
    doctorMyPatients: 'Mes patients',
    doctorAssignedPatients: 'Patients assignés',
    doctorCompletedSessions: 'Séances terminées',
    doctorPendingSessions: 'Séances en attente',
    doctorAvgAdherence: 'Adhérence moyenne',
    doctorShortPrefix: 'Dr.',
    doctorDashboardSubtitle: 'Gérez vos patients assignés et leurs plans de traitement',
    doctorClinicalSnapshot: 'Aperçu clinique',
    doctorTodayPanel: "Panel d'aujourd'hui",
    doctorHighestPainTrend: 'Tendance de douleur la plus élevée',
    doctorNoHighRiskAlerts: 'Aucune alerte de risque élevé pour le moment. Assignez des patients pour suivre les tendances.',
    doctorExercisesLogged: 'Exercices enregistrés',
    doctorAvgPain: 'Douleur moyenne',
    doctorAssignPatient: 'Assigner un patient',
    doctorSearchPatients: 'Rechercher par nom, e-mail ou état',
    doctorSortName: 'Trier: Nom (A-Z)',
    doctorSortCompletion: 'Trier: Taux de réalisation',
    doctorSortPain: 'Trier: Douleur moyenne',
    doctorSortPending: 'Trier: Séances en attente',
    doctorAllAdherenceBands: 'Toutes les bandes d’adhérence',
    doctorHighAdherence: 'Adhérence élevée (75%+)',
    doctorMediumAdherence: 'Adhérence moyenne (40-74%)',
    doctorLowAdherence: 'Faible adhérence (<40%)',
    doctorNoPatientsAssigned: 'Aucun patient assigné pour le moment',
    doctorAssignPatientsToStart: 'Assignez des patients pour commencer',
    doctorNoPatientsAvailable: 'Aucun patient disponible dans le système',
    doctorNoMatchingPatients: 'Aucun patient correspondant',
    doctorTryDifferentSearch: 'Essayez une autre recherche ou ajustez le filtre d’adhérence',
    mainDashboardWelcomeTitle: 'Bienvenue sur le tableau de bord RehabAI',
    mainDashboardLoginPrompt: 'Veuillez vous connecter pour accéder aux fonctionnalités du tableau de bord.',
    mainDashboardWelcomeUser: 'Bienvenue',
    mainDashboardLoggedInAs: 'Vous êtes connecté en tant que',
    mainDashboardPatients: 'Patients',
    mainDashboardPatientsDesc: 'Gérez les informations et la progression des patients',
    mainDashboardViewPatients: 'Voir les patients',
    mainDashboardExercisesDesc: 'Parcourez et créez des exercices de rééducation',
    mainDashboardViewExercises: 'Voir les exercices',
    mainDashboardSessions: 'Séances',
    mainDashboardSessionsDesc: 'Suivez les séances d’exercices et la progression',
    mainDashboardViewSessions: 'Voir les séances'
  }
};

export const supportedLanguages = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fr', label: 'Français' }
];

const normalizeLanguage = (value) => {
  if (!value) return 'en';
  const normalized = String(value).toLowerCase().split('-')[0];
  return translations[normalized] ? normalized : 'en';
};

const resolveTranslation = (dictionary, key) => {
  if (!dictionary || !key) return undefined;
  return key.split('.').reduce((currentValue, segment) => currentValue?.[segment], dictionary);
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const storedLanguage = localStorage.getItem('appLanguage');
    if (storedLanguage) {
      return normalizeLanguage(storedLanguage);
    }

    return normalizeLanguage(navigator.language || 'en');
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = useMemo(() => {
    return (key) => resolveTranslation(translations[language], key) || resolveTranslation(translations.en, key) || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: (nextLanguage) => setLanguage(normalizeLanguage(nextLanguage)), t, supportedLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};
